[package]
name = "qiniu-credential"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu Credential SDK for Rust"
keywords = ["qiniu", "storage"]

[dependencies]
hmac = "0.11.0"
sha-1 = "0.9.6"
url = "2.2.2"
once_cell = "1.8.0"
http = "0.2.4"

qiniu-utils = { version = "0.0.4", path = "../utils" }
mime = "0.3.16"

[dev-dependencies]
async-std = { version = "1.9.0", features = ["attributes"] }

[features]
default = []
async = []
docs = []

[package.metadata.docs.rs]
features = ["docs", "async"]
rustdoc-args = ["--cfg", "feature=\"docs\""]
