language: rust
matrix:
  include:
    - os: linux
      dist: bionic
      rust:
        - 1.42.0
      before_script:
        - sudo apt update -yqq
        - sudo apt install -yqq libcurl4 libssl-dev build-essential pkg-config
      script:
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make build test doc
            fi
    - os: osx
      rust:
        - 1.42.0
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
      before_script:
        - brew install curl pkg-config
      script:
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make build test doc
            fi
    - os: windows
      rust:
        - 1.42.0-x86_64-pc-windows-msvc
      before_script:
        - choco install make --force
        - choco install curl --force
      script:
        - |
            if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
              make build test doc
            fi
