[workspace]

members = [
    "credential",
    "utils",
    "etag",
    "upload_token",
    "http",
    "http-reqwest",
    "http-isahc",
    "http-ureq",
    "http-client",
    "api-generator",
    "apis",
]

[profile.release]
lto = "fat"
codegen-units = 1
