[package]
name = "qiniu-http"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu HTTP Interface for Rust"
keywords = ["qiniu", "storage"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc_version_runtime = "0.1.5"
assert-impl = "0.1.3"
once_cell = "1.4.1"
futures = { version = "0.3.5", optional = true }
async-fs = { version = "1.1.2", optional = true }
blocking = { version = "0.6.1", optional = true }

qiniu-utils = { version = "0.0.4", path = "../utils" }

[dev-dependencies]
async-std = { version = "1.6.3", features = ["attributes"] }

[features]
default = []
async = ["futures", "async-fs", "blocking"]
docs = []

[package.metadata.docs.rs]
features = ["docs", "async"]
rustdoc-args = ["--cfg", "feature=\"docs\""]
