[package]
name = "qiniu-utils"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2021"
rust-version = "1.56.0"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu SDK Utilities for Rust"
keywords = ["qiniu", "storage"]

[dependencies]
base64 = "0.13.0"
serde = "1.0.130"
smallvec = "1.7.0"

[dev-dependencies]
bincode = "1.0"
