[package]
name = "qiniu-apis"
version = "0.0.4"
authors = ["Rong Zhou <zhourong@qiniu.com>", "Shanghai Qiniu Information Technologies Co., Ltd."]
edition = "2018"
license = "Apache-2.0"
homepage = "https://www.qiniu.com"
description = "Qiniu APIs SDK for Rust"
keywords = ["qiniu", "storage"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.5", optional = true }

qiniu-http = { version = "0.0.4", path = "../http" }

[dev-dependencies]
async-std = { version = "1.6.3", features = ["attributes"] }

[features]
default = []
async = ["futures", "qiniu-http/async"]
docs = []

[package.metadata.docs.rs]
features = ["docs", "async"]
rustdoc-args = ["--cfg", "feature=\"docs\""]
