on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
name: Run Test Cases
jobs:
  linux:
    name: CI Test On Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.56.0
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install -yqq libkrb5-dev
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          default: true
          override: true
      - name: Test
        run: |
          rustup default ${{ matrix.rust }}
          make build clippy test
  macos:
    name: CI Test On macOS
    runs-on: macos-latest
    strategy:
      matrix:
        rust:
          - 1.56.0
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install make
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          default: true
          override: true
      - name: Test
        run: |
          rustup default ${{ matrix.rust }}
          make build clippy test
  windows:
    name: CI Test On Windows
    runs-on: windows-latest
    strategy:
      matrix:
        rust:
          - 1.56.0
          - stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Visual Studio Dev cmds
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install vcpkg
        uses: lukka/run-vcpkg@main
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgArguments: 'sqlite3'
          vcpkgTriplet: 'x64-windows'
          vcpkgGitCommitId: '30124253eecff36bc90f73341edbfb4f845e2a1e'
      - name: Install openssl
        run: |
          $VCPKG_ROOT/vcpkg install openssl --triplet x64-windows
        shell: bash
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
          default: true
          override: true
      - name: Test
        run: |
          rustup default ${{ matrix.rust }}
          make build clippy test
        env:
          RUST_LOG: "debug"
          RUST_BACKTRACE: "1"
          OPENSSL_DIR: "${{ github.workspace }}/vcpkg/packages/openssl_x64-windows"
